Repository softeerbootcamp4th/Team8-PineApple-FE, pull requests merged in 2024-08, with the labels that each got.

#38 Feat/#35/phone auth modal
  src/components/header/Header.jsx
  src/components/modal/PhoneAuthModal.jsx
  src/components/modal/PhoneInputModal.jsx
  src/pages/eventIntro/EventIntro.jsx
  src/pages/eventIntro/EventIntroMain.jsx
  src/pages/joinEvent/commentList/CommentIndex.jsx
  src/pages/joinEvent/commentList/EachComment.jsx
  src/pages/newCarIntro/NewCarCarousel.jsx
  src/utils/dateFormatting.js
Labels: enhancement

#43 don MiniQuiz layer and add images
  src/pages/joinEvent/JoinEventIntro.jsx
  src/pages/joinEvent/MiniQuiz.jsx
  src/pages/joinEvent/WorldCup.jsx
  src/styles/global.css
Labels: enhancement

#46 Feat/#40/comment api
  src/assets/images/eventIntroNav1.png
  src/assets/images/eventIntroNav1.svg
  src/assets/images/eventIntroNav2.png
  src/assets/images/eventIntroNav2.svg
  src/assets/images/eventIntroNav3.png
  src/assets/images/eventIntroNav3.svg
  src/assets/images/eventIntroNav4.png
  src/assets/images/eventIntroNav4.svg
  src/components/header/Header.jsx
  src/components/modal/CommandInputModal.jsx
  src/components/modal/PhoneAuthModal.jsx
  src/components/modal/PhoneInputModal.jsx
  src/pages/eventIntro/EventIntroNav.jsx
  src/pages/joinEvent/commentList/CommentDate.jsx
  src/pages/joinEvent/commentList/CommentIndex.jsx
  src/pages/joinEvent/commentList/CommentToggleButton.jsx
  src/pages/joinEvent/commentList/EachComment.jsx
  src/pages/joinEvent/commentList/PagingComment.jsx
  src/pages/joinEvent/commentList/RefreshData.jsx
  src/utils/timeFormatting.js
Labels: enhancement

#48 Feat/#47/auth context
  .gitignore
  src/api/auth/index.jsx
  src/api/comment/index.jsx
  src/api/index.jsx
  src/api/miniQuiz/index.jsx
  src/api/rapple/index.jsx
  src/api/worldCup/index.jsx
  src/components/header/Header.jsx
  src/components/modal/CommandInputModal.jsx
  src/components/modal/PhoneAuthModal.jsx
  src/components/modal/PhoneInputModal.jsx
  src/context/authContext.jsx
  src/pages/joinEvent/commentList/CommentIndex.jsx
  src/utils/phoneNumberFormatting.js
Labels: enhancement

#49 Feat/#44/get modal
  src/assets/images/carShadow.svg
  src/assets/images/getCarModalImage.svg
  src/components/buttons/BlueButton.jsx
  src/components/buttons/BluePurpleButton.jsx
  src/components/buttons/WhiteButton.jsx
  src/components/footer/Footer.jsx
  src/components/modal/GetCarModal.jsx
  src/pages/joinEvent/Card1.jsx
  src/pages/joinEvent/Card2.jsx
  src/pages/joinEvent/JoinEventIntroMain.jsx
  src/pages/joinEvent/MiniQuiz.jsx
  src/pages/joinEvent/WorldCup.jsx
  src/pages/newCarIntro/NewCarIntro.jsx
  src/pages/newCarIntro/NewCarIntroMain.jsx
  src/styles/global.css
  tailwind.config.js
Labels: enhancement

#51 Feat/#50/constant
  src/components/modal/CommandInputModal.jsx
  src/components/modal/PhoneAuthModal.jsx
  src/components/modal/PhoneInputModal.jsx
  src/constants/eventIntro/EventIntroNavData.jsx
  src/constants/newCarIntro/newCarDetailData.jsx
  src/hooks/useScroll.js
  src/pages/eventIntro/EventIntroNav.jsx
  src/pages/eventIntro/EventIntroNavItem.jsx
  src/pages/joinEvent/DailyComment.jsx
  src/pages/joinEvent/JoinEventIntro.jsx
  src/pages/newCarIntro/NewCarDetail.jsx
Labels: enhancement

#55 Feat/#52/world cup
  src/assets/images/casper_car_image.png
  src/assets/images/casper_car_image.svg
  src/assets/images/worldCupImage/hoverImage1.svg
  src/assets/images/worldCupImage/hoverImage2.svg
  src/assets/images/worldCupImage/hoverImage3.svg
  src/assets/images/worldCupImage/hoverImage4.svg
  src/assets/images/worldCupImage/hoverImage5.svg
  src/assets/images/worldCupImage/hoverImage6.svg
  src/assets/images/worldCupImage/nonHoverImage1.svg
  src/assets/images/worldCupImage/nonHoverImage2.svg
  src/assets/images/worldCupImage/nonHoverImage3.svg
  src/assets/images/worldCupImage/nonHoverImage4.svg
  src/assets/images/worldCupImage/nonHoverImage5.svg
  src/assets/images/worldCupImage/nonHoverImage6.svg
  src/assets/images/worldCupImage/resultImage1.svg
  src/assets/images/worldCupImage/resultImage2.svg
  src/assets/images/worldCupImage/resultImage3.svg
  src/assets/images/worldCupImage/resultImage4.svg
  src/assets/images/worldCupImage/resultImage5.svg
  src/assets/images/worldCupImage/resultImage6.svg
  src/constants/worldCup/worldCupData.jsx
  src/hooks/useScroll.js
  src/pages/eventIntro/EventIntroMain.jsx
  src/pages/joinEvent/DailyComment.jsx
  src/pages/joinEvent/JoinEventIntro.jsx
  src/pages/joinEvent/WorldCup.jsx
  src/pages/joinEvent/commentList/CommentDate.jsx
  src/pages/joinEvent/commentList/CommentIndex.jsx
  src/pages/joinEvent/commentList/EachComment.jsx
  src/pages/worldCup/WorldCupGame.jsx
  src/pages/worldCup/WorldCupHeader.jsx
  src/pages/worldCup/WorldCupTitle.jsx
  src/router.jsx
Labels: enhancement

#57 [feat] worldCup select animation effect
  src/pages/worldCup/WorldCupGame.jsx
  src/pages/worldCup/WorldCupHeader.jsx
  src/pages/worldCup/WorldCupTitle.jsx
  tailwind.config.js
Labels: enhancement

#58 Feat/#57/world cup detail
  src/App.jsx
  src/components/header/EventHeader.jsx
  src/pages/joinEvent/WorldCup.jsx
  src/pages/worldCup/WorldCupGame.jsx
Labels: fix

#61 Feat/#59/world cup result
  src/App.jsx
  src/api/auth/index.jsx
  src/api/comment/index.jsx
  src/api/index.jsx
  src/assets/icons/back.svg
  src/assets/icons/worldCupArrowIcon.svg
  src/assets/images/worldCupImage/resultImage1.svg
  src/assets/images/worldCupImage/resultImage2.svg
  src/assets/images/worldCupImage/resultImage3.svg
  src/assets/images/worldCupImage/resultImage4.svg
  src/assets/images/worldCupImage/resultImage5.svg
  src/assets/images/worldCupImage/resultImage6.svg
  src/components/header/EventHeader.jsx
  src/components/header/Header.jsx
  src/components/modal/CommandInputModal.jsx
  src/components/modal/ExitModal.jsx
  src/hooks/useScroll.js
  src/pages/joinEvent/DailyComment.jsx
  src/pages/miniquiz/MiniQuiz.jsx
  src/pages/miniquiz/MiniQuizResult.jsx
  src/pages/worldCup/WorldCupGame.jsx
  src/pages/worldCup/WorldCupMain.jsx
  src/pages/worldCup/WorldCupResult.jsx
  src/router.jsx
Labels: enhancement, fix

#63 Feat/#62/world cup result bottom
  src/assets/images/worldCupImage/backImage1.svg
  src/assets/images/worldCupImage/backImage2.svg
  src/assets/images/worldCupImage/backImage3.svg
  src/assets/images/worldCupImage/backImage4.svg
  src/assets/images/worldCupImage/backImage5.svg
  src/assets/images/worldCupImage/backImage6.svg
  src/assets/images/worldCupImage/frontImage1.svg
  src/assets/images/worldCupImage/frontImage2.svg
  src/assets/images/worldCupImage/frontImage3.svg
  src/assets/images/worldCupImage/frontImage4.svg
  src/assets/images/worldCupImage/frontImage5.svg
  src/assets/images/worldCupImage/frontImage6.svg
  src/components/header/EventHeader.jsx
  src/constants/worldCup/worldCupResultData.jsx
  src/pages/worldCup/WorldCupResult.jsx
  src/pages/worldCup/WorldCupResultBottom.jsx
  src/pages/worldCup/WorldCupResultItem.jsx
  src/pages/worldCup/WorldCupResultTop.jsx
Labels: enhancement

#66 Feat/#64/world cup result bottom front
  src/assets/icons/blueTriangle.svg
  src/assets/icons/checkbox.svg
  src/assets/icons/grayTriangle.svg
  src/assets/images/worldCupImage/frontImage1.svg
  src/assets/images/worldCupImage/frontImage2.svg
  src/assets/images/worldCupImage/frontImage3.svg
  src/assets/images/worldCupImage/frontImage4.svg
  src/assets/images/worldCupImage/frontImage5.svg
  src/assets/images/worldCupImage/frontImage6.svg
  src/components/header/EventHeader.jsx
  src/components/toastMessage/ToastMessage.jsx
  src/hooks/useScroll.js
  src/hooks/useToast.js
  src/pages/joinEvent/DailyComment.jsx
  src/pages/worldCup/WorldCupResult.jsx
  src/pages/worldCup/WorldCupResultBottom.jsx
  src/pages/worldCup/WorldCupResultItem.jsx
  src/pages/worldCup/WorldCupResultTop.jsx
  src/styles/global.css
  src/styles/worldCupResult.css
Labels: enhancement, fix

#71 Feat/#70/worldCupApi
  src/api/worldCup/index.jsx
  src/components/header/Header.jsx
  src/components/modal/AlreadyGetCarModal.jsx
  src/components/modal/GetCarModal.jsx
  src/components/modal/PhoneAuthModal.jsx
  src/components/modal/PhoneInputModal.jsx
  src/pages/joinEvent/Card1.jsx
  src/pages/worldCup/WorldCupMain.jsx
  src/pages/worldCup/WorldCupResult.jsx
  src/pages/worldCup/WorldCupResultBottom.jsx
  src/pages/worldCup/WorldCupResultTop.jsx
Labels: enhancement, fix

#76 Feat/#75/disable button
  src/hooks/useMiniQuiz.js
  src/pages/joinEvent/MiniQuiz.jsx
  src/pages/miniquiz/InvalidAccess.jsx
  src/pages/miniquiz/LoadingQuiz.jsx
  src/pages/miniquiz/MiniQuiz.jsx
  src/pages/miniquiz/NoQuiz.jsx
  src/router.jsx
Labels: fix

#79 Feat/#72/comment like api
  src/api/comment/index.jsx
  src/components/header/EventHeader.jsx
  src/components/modal/AlreadyGetCarModal.jsx
  src/components/modal/CommentInputModal.jsx
  src/components/modal/GetItemModal.jsx
  src/components/modal/PhoneAuthModal.jsx
  src/constants/eventIntro/EventIntroNavData.jsx
  src/hooks/useToast.js
  src/pages/eventIntro/EventIntroNav.jsx
  src/pages/joinEvent/DailyComment.jsx
  src/pages/joinEvent/commentList/CommentIndex.jsx
  src/pages/joinEvent/commentList/EachComment.jsx
  src/pages/miniquiz/MiniQuizResult.jsx
  src/pages/worldCup/WorldCupGame.jsx
  src/pages/worldCup/WorldCupMain.jsx
  src/pages/worldCup/WorldCupResultBottom.jsx
  src/pages/worldCup/WorldCupResultTop.jsx
Labels: enhancement, fix

#81 Feat/#80/modalIndex
  index.html
  src/assets/images/getItemModalImage.svg
  src/components/buttons/BlueButton.jsx
  src/components/modal/AlreadyGetCarModal.jsx
  src/components/modal/CommentInputModal.jsx
  src/components/modal/ExitModal.jsx
  src/components/modal/GetItemModal.jsx
  src/components/modal/ModalFrame.jsx
  src/components/modal/ModalPortal.jsx
  src/components/modal/PhoneAuthModal.jsx
  src/components/modal/PhoneInputModal.jsx
  src/hooks/useBeforeUnload.js
  src/pages/joinEvent/DailyComment.jsx
  src/pages/worldCup/WorldCupGame.jsx
  src/pages/worldCup/WorldCupResult.jsx
  src/pages/worldCup/WorldCupResultTop.jsx
  src/styles/global.css
Labels: enhancement, fix

#85 Feat/#83/eventResultModal
  src/App.jsx
  src/api/auth/index.jsx
  src/api/comment/index.jsx
  src/api/index.jsx
  src/api/rapple/index.jsx
  src/api/worldCup/index.jsx
  src/assets/icons/blueBar.svg
  src/assets/icons/blueCheckIcon.svg
  src/components/header/Header.jsx
  src/components/modal/CommentInputModal.jsx
  src/components/modal/EventResultModal.jsx
  src/components/modal/GetItemModal.jsx
  src/components/modal/PhoneAuthModal.jsx
  src/components/modal/PrizeLinkSentModal.jsx
  src/context/authContext.jsx
  src/pages/joinEvent/Card1.jsx
  src/pages/joinEvent/JoinEventIntroMain.jsx
  src/pages/joinEvent/Reward.jsx
  src/pages/joinEvent/commentList/CommentIndex.jsx
  src/pages/joinEvent/commentList/EachComment.jsx
  src/pages/worldCup/WorldCupMain.jsx
  src/router.jsx
Labels: enhancement, fix

#86 Feat/#82/rewardBugFix
  src/api/rapple/index.jsx
  src/components/modal/EventResultModal.jsx
  src/components/modal/GetItemModal.jsx
  src/components/modal/ModalFrame.jsx
  src/components/modal/PrizeLinkSentModal.jsx
  src/constants/worldCup/worldCupData.jsx
  src/constants/worldCup/worldCupResultData.jsx
  src/pages/joinEvent/Reward.jsx
  src/pages/joinEvent/commentList/CommentToggleButton.jsx
  src/pages/joinEvent/commentList/EachComment.jsx
Labels: bug, fix

#87 Feat/#77/get item
  src/api/miniQuiz/index.jsx
  src/components/modal/GetOrdermodal.jsx
  src/components/modal/GetToolBoxModal.jsx
  src/pages/joinEvent/Card2.jsx
  src/pages/miniquiz/ButtonCases.jsx
  src/pages/miniquiz/MiniQuizResultMain.jsx
Labels: enhancement

#88 Bugfix
  service/src/components/modal/GetOrderPrizeModal.jsx
  service/src/components/modal/GetToolBoxModal.jsx
  service/src/constants/eventIntro/EventIntroNavData.jsx
  service/src/pages/miniquiz/MiniQuizMain.jsx
  service/src/pages/miniquiz/MiniQuizResultMain.jsx
  service/src/pages/miniquiz/SubmitButton.jsx
  service/src/styles/newCarCarousel.css
Labels: bug

#90 Feat/#89/eventAdminHeader
  service/src/components/header/AdminHeader.jsx
  service/src/components/modal/PhoneAuthModal.jsx
  service/src/pages/admin/AdminEditEvent.jsx
  service/src/pages/admin/AdminIndex.jsx
  service/src/pages/eventIntro/EventIntroMain.jsx
  service/src/pages/joinEvent/commentList/RefreshData.jsx
  service/src/router.jsx
  service/src/styles/global.css
Labels: enhancement, fix

#94 Feat/#91/adminEditEvent
  .github/workflows/service-cicd.yml
  service/src/assets/icons/imageAddIcon.svg
  service/src/components/buttons/BlackButton.jsx
  service/src/pages/admin/AdminEditEvent.jsx
  service/src/pages/admin/adminEditEvent/AdminEditEvent.jsx
  service/src/pages/admin/adminEditEvent/AdminEditHeader.jsx
  service/src/pages/admin/adminEditEvent/adminEditMiniQuiz/AdminEditMiniQuiz.jsx
  service/src/pages/admin/adminEditEvent/adminEditMiniQuiz/AdminEditMiniQuizContent.jsx
  service/src/pages/admin/adminEditEvent/adminEditMiniQuizAnswer/AdminEditMiniQuizAnswer.jsx
  service/src/pages/admin/adminEditEvent/adminEditMiniQuizAnswer/AdminEditMiniQuizAnswerContent.jsx
  service/src/router.jsx
Labels: enhancement

#99 Feat/#92/admin event status
  admin/src/pages/AdminEventStatus/AdminEventStatus.jsx
  admin/src/pages/AdminEventStatus/EntryRow.jsx
  admin/src/pages/AdminEventStatus/EntryTable.jsx
  admin/src/pages/AdminEventStatus/PageButton.jsx
  admin/src/pages/AdminEventStatus/PrizeTable.jsx
  admin/src/pages/AdminEventStatus/TableComponent.jsx
  service/index.html
Labels: enhancement

#102 Feat/#98/adminCalender
  admin/src/App.jsx
  admin/src/components/buttons/BlackButton.jsx
  admin/src/components/form/ImageUploader.jsx
  admin/src/components/form/InputForm.jsx
  admin/src/components/header/AdminEditHeader.jsx
  admin/src/components/header/AdminHeader.jsx
  admin/src/context/dateContext.jsx
  admin/src/main.jsx
  admin/src/pages/AdminIndex.jsx
  admin/src/pages/adminEditEvent/AdminEditEvent.jsx
  admin/src/pages/adminEditEvent/AdminEditHeader.jsx
  admin/src/pages/adminEditEvent/adminEditDraw/AdminEditDrawContent.jsx
  admin/src/pages/adminEditEvent/adminEditMiniQuiz/AdminEditMiniQuizContent.jsx
  admin/src/pages/adminEditEvent/adminEditMiniQuizAnswer/AdminEditMiniQuizAnswerContent.jsx
  admin/src/pages/draw/Draw.jsx
  admin/src/pages/draw/DrawContent.jsx
  admin/src/pages/miniQuiz/MiniQuiz.jsx
  admin/src/pages/miniQuiz/MiniQuizContent.jsx
  admin/src/pages/miniQuizAnswer/MiniQuizAnswer.jsx
  admin/src/pages/miniQuizAnswer/MiniQuizAnswerContent.jsx
  admin/src/pages/reward/Reward.jsx
  admin/src/pages/reward/RewardContent.jsx
  admin/src/router.jsx
  admin/src/utils/dateFormatting.js
Labels: enhancement, fix

#104 Feat/#103/api 연동 및 tab 추가 및 공통 모달 추가
  admin/src/App.jsx
  admin/src/api/index.js
  admin/src/api/miniQuiz/index.js
  admin/src/api/miniQuizAnswer/index.js
  admin/src/components/header/TabHeader.jsx
  admin/src/components/modal/ModalFrame.jsx
  admin/src/components/modal/ModalPortal.jsx
  admin/src/hooks/useFetch.js
  admin/src/pages/draw/Draw.jsx
  admin/src/pages/miniQuiz/MiniQuiz.jsx
  admin/src/pages/miniQuiz/MiniQuizContent.jsx
  admin/src/pages/miniQuizAnswer/MiniQuizAnswer.jsx
  admin/src/pages/miniQuizAnswer/MiniQuizAnswerContent.jsx
Labels: enhancement

#105 Feat/admin upload reward
  admin/package.json
  admin/src/api/UploadReward/index.js
  admin/src/api/indexFormData.js
  admin/src/components/buttons/BlackButton.jsx
  admin/src/components/header/NavLinkItem.jsx
  admin/src/components/header/TabHeader.jsx
  admin/src/pages/AdminEventStatus/AdminEventStatus.jsx
  admin/src/pages/UploadReward/UploadReward.jsx
  admin/src/pages/draw/Draw.jsx
  admin/src/pages/miniQuiz/MiniQuiz.jsx
  admin/src/pages/miniQuizAnswer/MiniQuizAnswer.jsx
  admin/src/pages/reward/Reward.jsx
  admin/src/router.jsx
  admin/yarn.lock
Labels: enhancement

#107 changed_layout
  service/src/pages/miniquiz/MiniQuizResult.jsx
  service/src/pages/miniquiz/MiniQuizResultMain.jsx
Labels: fix

#109 Feat/#108/adminLoginPage
  admin/src/App.jsx
  admin/src/api/auth/index.js
  admin/src/api/index.js
  admin/src/api/miniQuiz/index.js
  admin/src/components/buttons/BlackButton.jsx
  admin/src/hooks/useFetch.js
  admin/src/pages/ErrorPage.jsx
  admin/src/pages/ProtectedRoute.jsx
  admin/src/pages/login/Login.jsx
  admin/src/pages/miniQuiz/MiniQuiz.jsx
  admin/src/pages/miniQuiz/MiniQuizContent.jsx
  admin/src/router.jsx
  admin/src/utils/isValidPhoneNumber.js
  admin/src/utils/phoneNumberFormatting.js
  service/src/components/buttons/BlackButton.jsx
Labels: enhancement, fix

#112 Feat/#111/AdminDrawApi 연동 및 useBlocker 추가
  admin/src/api/draw/index.js
  admin/src/api/index.js
  admin/src/api/miniQuizAnswer/index.js
  admin/src/components/form/ImageUploader.jsx
  admin/src/components/header/AdminHeader.jsx
  admin/src/components/modal/ModalFrame.jsx
  admin/src/hooks/useFormData.js
  admin/src/pages/draw/Draw.jsx
  admin/src/pages/draw/DrawContent.jsx
  admin/src/pages/miniQuiz/MiniQuiz.jsx
  admin/src/pages/miniQuizAnswer/MiniQuizAnswer.jsx
  admin/src/pages/miniQuizAnswer/MiniQuizAnswerContent.jsx
Labels: enhancement, fix

#113 Feat/#110/analytic page layout
  .github/workflows/admin-cicd.yml
  .github/workflows/service-cicd.yml
  admin/src/App.jsx
  admin/src/api/UploadPrize/index.js
  admin/src/api/UploadReward/index.js
  admin/src/api/_index.js
  admin/src/api/indexFormData.js
  admin/src/components/header/TabHeader.jsx
  admin/src/pages/AnalyticsPage/AnalyticsPage.jsx
  admin/src/pages/AnalyticsPage/TableHeader.jsx
  admin/src/pages/AnalyticsPage/TableRow.jsx
  admin/src/pages/UploadPrize/UploadPrize.jsx
  admin/src/pages/UploadReward/UploadReward.jsx
  admin/src/router.jsx
  admin/yarn.lock
Labels: enhancement

#116 Feat/#114/indicator api
  admin/src/api/AdminEventStatus/index.js
  admin/src/api/Indicator/index.js
  admin/src/api/UploadPrize/index.js
  admin/src/api/UploadReward/index.js
  admin/src/api/_index.js
  admin/src/components/header/TabHeader.jsx
  admin/src/pages/AdminEventStatus/EntryRow.jsx
  admin/src/pages/AdminEventStatus/EntryTable.jsx
  admin/src/pages/AdminEventStatus/PrizeTable.jsx
  admin/src/pages/AnalyticsPage/AnalyticsPage.jsx
  admin/src/pages/Indicator/Dau.jsx
  admin/src/pages/Indicator/Indicator.jsx
  admin/src/pages/Indicator/TableHeader.jsx
  admin/src/pages/Indicator/TableRow.jsx
  admin/src/pages/UploadPrize/UploadPrize.jsx
  admin/src/pages/UploadReward/UploadReward.jsx
  admin/src/router.jsx
Labels: enhancement

#119 Feat/#118/eventCommentDetail
  service/src/components/modal/CommentInputModal.jsx
  service/src/components/modal/CommentModal.jsx
  service/src/pages/eventIntro/EventIntroNav.jsx
  service/src/pages/eventIntro/EventIntroNavItem.jsx
  service/src/pages/eventIntro/EventIntroRewards.jsx
  service/src/pages/joinEvent/commentList/CommentDetail.jsx
  service/src/pages/joinEvent/commentList/CommentIndex.jsx
  service/src/pages/joinEvent/commentList/EachComment.jsx
  service/src/router.jsx
  service/src/utils/isValidPhoneNumber.js
Labels: enhancement, fix

#123 Feat/#122/shared link
  service/src/App.jsx
  service/src/api/comment/index.jsx
  service/src/api/rapple/index.jsx
  service/src/components/modal/CommentModal.jsx
  service/src/components/toastMessage/ToastMessage.jsx
  service/src/hooks/useToast.js
  service/src/pages/eventIntro/EventIntroRewards.jsx
  service/src/pages/joinEvent/DailyComment.jsx
  service/src/pages/joinEvent/commentList/CommentDetail.jsx
  service/src/pages/joinEvent/commentList/EachComment.jsx
  service/src/pages/joinEvent/commentList/Redirect.jsx
  service/src/pages/worldCup/WorldCupResultTop.jsx
  service/src/router.jsx
  service/src/utils/shortDateFormat.js
Labels: enhancement, fix

#127 Feat/#124/admin date change
  admin/src/App.jsx
  admin/src/api/header/index.js
  admin/src/components/header/AdminHeader.jsx
  admin/src/components/header/NavLinkItem.jsx
  admin/src/components/header/TabHeader.jsx
  admin/src/main.jsx
  admin/src/pages/UploadPrize/UploadPrize.jsx
  admin/src/pages/UploadReward/UploadReward.jsx
  admin/src/router.jsx
Labels: enhancement

#130 Feat/#129/FramerMotion
  service/package.json
  service/src/components/buttons/BlueButton.jsx
  service/src/components/modal/CommentInputModal.jsx
  service/src/components/modal/ModalFrame.jsx
  service/src/components/modal/PhoneAuthModal.jsx
  service/src/components/modal/PhoneInputModal.jsx
  service/src/pages/eventIntro/EventIntro.jsx
  service/src/pages/eventIntro/EventIntroMain.jsx
  service/src/pages/eventIntro/EventIntroNav.jsx
  service/src/pages/eventIntro/EventIntroRewards.jsx
  service/src/pages/joinEvent/JoinEventIntroMain.jsx
  service/src/pages/newCarIntro/NewCarCarousel.jsx
  service/src/pages/newCarIntro/NewCarIntroMain.jsx
  service/src/styles/FramerMotion.js
  service/yarn.lock
Labels: enhancement, fix

#142 Feat/#140/slowAnimation
  service/src/api/comment/index.jsx
  service/src/pages/eventIntro/EventIntro.jsx
  service/src/pages/eventIntro/EventIntroNav.jsx
  service/src/pages/eventIntro/EventIntroRewards.jsx
  service/src/pages/joinEvent/commentList/EachComment.jsx
  service/src/pages/joinEvent/commentList/Redirect.jsx
  service/src/pages/worldCup/WorldCupGame.jsx
  service/src/pages/worldCup/WorldCupMain.jsx
  service/src/pages/worldCup/WorldCupResultTop.jsx
Labels: fix

#141 Fix/#138/admin navigation error
  admin/package.json
  admin/src/api/DrawCasper/index.js
  admin/src/components/header/AdminHeader.jsx
  admin/src/components/header/TabHeader.jsx
  admin/src/hooks/useFetch.js
  admin/src/pages/AdminEventStatus/EntryRow.jsx
  admin/src/pages/Indicator/TableHeader.jsx
  admin/src/pages/UploadPrize/UploadPrize.jsx
  admin/src/pages/UploadReward/UploadReward.jsx
  admin/src/pages/drawCasper/DrawCasper.jsx
  admin/src/router.jsx
  admin/yarn.lock
  service/src/components/buttons/BlueButton.jsx
  service/src/components/buttons/BluePurpleButton.jsx
  service/src/components/buttons/WhiteButton.jsx
  service/src/pages/joinEvent/CarCard.jsx
  service/src/pages/joinEvent/MiniQuiz.jsx
  service/src/pages/joinEvent/ToolBoxCard.jsx
  service/src/pages/miniquiz/ClickBox.jsx
  service/src/pages/miniquiz/LoadingQuiz.jsx
  service/src/pages/miniquiz/MiniQuiz.jsx
  service/src/pages/miniquiz/MiniQuizMain.jsx
  service/src/pages/miniquiz/NoQuizMain.jsx
  service/src/pages/miniquiz/SubmitButton.jsx
  service/src/pages/newCarIntro/NewCarCarousel.jsx
  service/src/styles/newCarCarousel.css
Labels: enhancement

#144 Feat/#143/SEOsetting
  service/index.html
  service/package.json
  service/public/hyundai.svg
  service/public/vite.svg
  service/robot.txt
  service/sitemap.xml
  service/src/App.jsx
  service/src/pages/eventIntro/EventIntro.jsx
  service/src/pages/joinEvent/JoinEventIntro.jsx
  service/src/pages/newCarIntro/NewCarIntro.jsx
  service/yarn.lock
Labels: enhancement

#147 Feat/#146/PreRendering
  service/index.html
  service/package.json
  service/robots.txt
  service/src/pages/eventIntro/EventIntro.jsx
  service/src/pages/joinEvent/JoinEventIntro.jsx
  service/src/pages/miniquiz/MiniQuiz.jsx
  service/src/pages/newCarIntro/NewCarIntro.jsx
  service/src/pages/worldCup/WorldCupMain.jsx
  service/vite.config.js
  service/yarn.lock
Labels: fix

#148 [fix] metaTag 수정
  service/index.html
  service/src/App.jsx
  service/src/pages/eventIntro/EventIntro.jsx
  service/src/pages/joinEvent/JoinEventIntro.jsx
  service/src/pages/miniquiz/MiniQuiz.jsx
  service/src/pages/newCarIntro/NewCarIntro.jsx
  service/src/pages/worldCup/WorldCupMain.jsx
Labels: fix

#153 Fix/#145/additional changes
  admin/index.html
  admin/public/hyundai.svg
  admin/public/vite.svg
  admin/src/components/form/InputForm.jsx
  admin/src/components/header/AdminHeader.jsx
  admin/src/pages/reward/Reward.jsx
  admin/src/pages/reward/RewardContent.jsx
  service/src/components/modal/AlreadyGetCarModal.jsx
  service/src/components/modal/ExitModal.jsx
  service/src/components/modal/GetItemModal.jsx
  service/src/constants/newCarIntro/newCarDetailData.jsx
  service/src/pages/joinEvent/CarCard.jsx
  service/src/pages/joinEvent/JoinEventIntroMain.jsx
  service/src/pages/joinEvent/MiniQuiz.jsx
  service/src/pages/joinEvent/ToolBoxCard.jsx
  service/src/pages/joinEvent/WorldCup.jsx
  service/src/pages/miniquiz/LoadingQuiz.jsx
  service/src/pages/miniquiz/MiniQuizResultMain.jsx
  service/src/pages/miniquiz/NoQuizMain.jsx
  service/src/pages/newCarIntro/NewCarCarousel.jsx
  service/src/pages/newCarIntro/NewCarDetail.jsx
  service/src/pages/newCarIntro/NewCarDetailBox.jsx
  service/src/utils/linkToFunc.js
  service/vite.config.js
Labels: fix

#155 Feat/#151/reward result fix
  service/package.json
  service/src/App.jsx
  service/src/assets/icons/Loading.svg
  service/src/components/modal/EventResultModal.jsx
  service/src/pages/joinEvent/JoinEventIntroMain.jsx
  service/src/pages/joinEvent/Reward.jsx
  service/src/pages/joinEvent/commentList/CommentDetail.jsx
  service/src/pages/joinEvent/commentList/Redirect.jsx
  service/src/styles/global.css
  service/yarn.lock
Labels: enhancement, fix

#157 [fix] AuthModalLogic fix
  service/src/components/modal/CommentModal.jsx
  service/src/components/modal/PhoneAuthModal.jsx
  service/src/pages/joinEvent/commentList/CommentDetail.jsx
Labels: fix

#158 [fix] AuthModalLogic fix
  service/src/components/modal/PhoneAuthModal.jsx
  service/src/components/modal/PhoneInputModal.jsx
Labels: fix

#160 Feat/#159/imageOptimize
  admin/src/pages/login/Login.jsx
  service/src/assets/icons/casperCarImageShadow.svg
  service/src/assets/images/1stPrize.png
  service/src/assets/images/1stPrizeCar.png
  service/src/assets/images/carShadow.svg
  service/src/assets/images/casperCarImageShadow.webp
  service/src/assets/images/casper_car_image.svg
  service/src/assets/images/casper_car_image.webp
  service/src/assets/images/prize2.png
  service/src/assets/images/prize3.png
  service/src/assets/images/prize4.png
  service/src/pages/eventIntro/EventIntroMain.jsx
  service/src/pages/eventIntro/EventIntroNavItem.jsx
  service/src/pages/worldCup/WorldCupGame.jsx
  service/src/pages/worldCup/WorldCupMain.jsx
Labels: fix

#164 Fix/#154/code
  admin/src/pages/UploadPrize/UploadPrize.jsx
  admin/src/pages/UploadReward/UploadReward.jsx
  service/src/components/SlideUpMotion/SlideUpMotion.jsx
  service/src/components/buttons/BaseButton.jsx
  service/src/components/buttons/BlueButton.jsx
  service/src/components/buttons/BluePurpleButton.jsx
  service/src/components/buttons/WhiteButton.jsx
  service/src/pages/eventIntro/EventIntro.jsx
  service/src/pages/eventIntro/EventIntroMain.jsx
  service/src/pages/eventIntro/EventIntroNav.jsx
  service/src/pages/joinEvent/CarCard.jsx
  service/src/pages/joinEvent/JoinEventIntroMain.jsx
  service/src/pages/joinEvent/ToolBoxCard.jsx
  service/src/pages/joinEvent/WorldCup.jsx
  service/src/pages/newCarIntro/NewCarCarousel.jsx
  service/src/pages/newCarIntro/NewCarDetail.jsx
  service/src/pages/newCarIntro/NewCarIntroMain.jsx
  service/src/pages/worldCup/WorldCupResultTop.jsx
  service/src/utils/linkToFunc.js
Labels: fix

#166 Feat/#165/funnel
  service/src/components/header/Header.jsx
  service/src/components/modal/PhoneAuthModal.jsx
  service/src/hooks/useFunnel.js
  service/src/pages/joinEvent/DailyComment.jsx
  service/src/pages/joinEvent/commentList/CommentIndex.jsx
  service/src/pages/joinEvent/commentList/PagingComment.jsx
  service/src/pages/worldCup/WorldCupResultTop.jsx
  service/src/styles/pagingComment.css
Labels: enhancement, fix

#167 Fix/#154/code
  service/src/pages/joinEvent/JoinEventIntroMain.jsx
  service/src/pages/joinEvent/MiniQuiz.jsx
  service/src/utils/miniQuizUtils.js
Labels: fix

#169 Feat/#168/mini quiz result modal
  service/public/sitemap.xml
  service/src/components/header/Header.jsx
  service/src/components/modal/GetItemModal.jsx
  service/src/pages/eventIntro/EventIntroMain.jsx
  service/src/pages/eventIntro/EventIntroRewards.jsx
  service/src/pages/miniquiz/MiniQuizResultMain.jsx
  service/src/pages/newCarIntro/NewCarIntro.jsx
  service/src/router.jsx
  service/vite.config.js
Labels: fix

#170 [fix] package 수정
  admin/package-lock.json
  admin/yarn.lock
  service/package-lock.json
  service/package.json
  service/yarn.lock
Labels: fix

#173 Feat/#172/404 page
  service/src/api/index.jsx
  service/src/components/modal/CommentInputModal.jsx
  service/src/components/modal/PhoneAuthModal.jsx
  service/src/components/modal/PhoneInputModal.jsx
  service/src/context/authContext.jsx
  service/src/pages/eventIntro/NotFound.jsx
  service/src/pages/joinEvent/Reward.jsx
  service/src/pages/joinEvent/commentList/CommentDetail.jsx
  service/src/pages/worldCup/WorldCupGame.jsx
  service/src/router.jsx
Labels: enhancement, fix

#174 Fix/#154/code
  .github/workflows/admin-cicd.yml
  .github/workflows/service-cicd.yml
  admin/src/components/header/AdminHeader.jsx
  admin/src/pages/AdminEventStatus/EntryTable.jsx
  admin/src/pages/AdminEventStatus/PageButton.jsx
  admin/src/pages/AdminEventStatus/RadioButton.jsx
  admin/src/pages/Indicator/Dau.jsx
  admin/src/pages/Indicator/TableRow.jsx
  admin/src/pages/UploadPrize/UploadPrize.jsx
  admin/src/pages/UploadReward/UploadReward.jsx
  admin/src/pages/drawCasper/DrawCasper.jsx
  admin/yarn.lock
  service/package.json
  service/src/components/buttons/BaseButton.jsx
  service/src/components/buttons/BlueButton.jsx
  service/src/components/buttons/BluePurpleButton.jsx
  service/src/components/buttons/WhiteButton.jsx
  service/src/pages/eventIntro/EventIntro.jsx
  service/src/pages/joinEvent/JoinEventIntro.jsx
  service/src/pages/joinEvent/WorldCup.jsx
  service/src/pages/miniquiz/ButtonCases.jsx
  service/src/pages/miniquiz/ClickBox.jsx
  service/src/pages/miniquiz/LoadingQuiz.jsx
  service/src/pages/miniquiz/MiniQuiz.jsx
  service/src/pages/miniquiz/MiniQuizMain.jsx
  service/src/pages/miniquiz/NoQuizMain.jsx
  service/src/pages/miniquiz/miniquizhooks/useMiniQuiz.js
  service/src/pages/newCarIntro/NewCarIntro.jsx
  service/src/pages/worldCup/WorldCupMain.jsx
  service/yarn.lock
Labels: fix

#175 fix/#154/code
  admin/yarn.lock
Labels: fix

#176 fix/#154/code
  .github/workflows/service-cicd.yml
  admin/src/pages/miniQuiz/MiniQuizContent.jsx
  admin/src/pages/reward/Reward.jsx
  service/src/pages/eventIntro/EventIntroRewards.jsx
  service/src/pages/miniquiz/LoadingQuiz.jsx
  service/src/pages/miniquiz/MiniQuizMain.jsx
  service/src/pages/miniquiz/SubmitButton.jsx
  service/src/pages/miniquiz/miniquizhooks/useMiniQuiz.js
Labels: fix
